apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dapi-envars-fieldref
  labels:
    app: dapi-envars-fieldref
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dapi-envars-fieldref
      name: dapi-envars-fieldref
      annotations:
        checksum/conf: "{{ toYaml .Values.conf | sha256sum }}"
    spec:
      containers:
        - name: test-container
          image: gcr.io/google_containers/busybox
          command: [ "sh", "-c"]
          args:
          - while true; do
              echo -en '\n';
              printenv MY_NODE_NAME MY_POD_NAME MY_POD_NAMESPACE;
              printenv MY_POD_IP MY_POD_SERVICE_ACCOUNT;
              printenv MY_HOST_NAME;
              printenv MY_VALUE;
              sleep 10;
            done;
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: MY_VALUE
              valueFrom:
                configMapKeyRef:
                  name: "mychart-configmap-{{ toYaml .Values.conf | sha256sum }}"
                  key: myvalue
